DevFramework.Northwind.MvcWebUI/Models/FaturaTurleriListViewModel.cs
using DevFramework.Northwind.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DevFramework.Northwind.MvcWebUI.Models
{
    public class FaturaTurleriListViewModel
    {
        public List<FaturaTurleri> faturaTurleris { get; set; }
        public FaturaTurleri faturaTurleriGet { get; set; }
    }
}

DevFramework.Northwind.MvcWebUI/Controllers/FaturaTurleriController.cs
using DevFramework.Northwind.Business.Abstract;
using DevFramework.Northwind.MvcWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DevFramework.Northwind.MvcWebUI.Controllers
{
    public class FaturaTurleriController : Controller
    {
        private IFaturaTurleriService _faturaTurleriService;
        public FaturaTurleriController(IFaturaTurleriService faturaTurleriService)
        {
            _faturaTurleriService = faturaTurleriService;
        }
        // GET: FaturaTurleri
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FaturaTurleriList()
        {
            return View();

        }
        public ActionResult FaturaTurleriGetir()
        {
            var model = new FaturaTurleriListViewModel
            {
                faturaTurleris = _faturaTurleriService.GetAll()
            };
            return Json(new { data = model.faturaTurleris }, JsonRequestBehavior.AllowGet);

        }
        //Fatura türlerini getirme forma
        [HttpGet]
        public ActionResult FaturaTurleriKayit(int id)
        {

            var model =new FaturaTurleriListViewModel
            {
                faturaTurleriGet = _faturaTurleriService.GetById(id)
            };
            return View(model);
        }
        //faturaturleri kaydetme ve güncelleme action
        [HttpPost]
        public ActionResult FaturaTurleriKayit(FaturaTurleriListViewModel faturaTurleries)
        {
            bool status = false;
            if (ModelState.IsValid)
            {

                if (faturaTurleries.faturaTurleriGet.Id > 0)
                {
                    //Edit 
                    var model = new FaturaTurleriListViewModel
                    {
                        faturaTurleriGet = _faturaTurleriService.Update(faturaTurleries.faturaTurleriGet)
                    };
                }
                else
                {
                    //Save
                    var model = new FaturaTurleriListViewModel
                    {
                        faturaTurleriGet = _faturaTurleriService.Add(faturaTurleries.faturaTurleriGet)
                    };

                }

                status = true;

            }
            return new JsonResult { Data = new { status = status } };
        }
        //fatura türleri göster 
        [HttpGet]
        public ActionResult FaturaTurleriSil(int id)
        {
            var model = new FaturaTurleriListViewModel
            {
                faturaTurleriGet = _faturaTurleriService.GetById(id)
            };
            return View(model);
        }
        //faturatürleri sil
        [HttpPost]
        [ActionName("FaturaTurleriSil")]
        public ActionResult Delete(int id)
        {
            bool status = false;
            if (id != 0)
            {
                _faturaTurleriService.Delete(id);
                status = true;
            }

            return new JsonResult { Data = new { status = status } };
        }
    }
}

DevFramework.Northwind.MvcWebUI/Views/FaturaTurleri/FaturaTurleriKayit.cshtml
@model DevFramework.Northwind.MvcWebUI.Models.FaturaTurleriListViewModel
@{
    Layout = null;
}


@using (Html.BeginForm("FaturaTurleriKayit", "FaturaTurleri", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model.faturaTurleriGet != null && Model.faturaTurleriGet.Id > 0)
    {
        @Html.HiddenFor(a => a.faturaTurleriGet.Id)
    }

    <div class="form-group">
        <label>Fatura Türü</label>
        @Html.TextBoxFor(a => a.faturaTurleriGet.FaturaTuru, new { @class = "form-control", @required = "required" })
        @Html.ValidationMessageFor(a => a.faturaTurleriGet.FaturaTuru)
    </div>


    <div>
        <input class="btn btn-success" type="submit" value="KAYIT" />
    </div>
}

DevFramework.Northwind.MvcWebUI/Views/FaturaTurleri/FaturaTurleriList.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>title</title>
    <!-- DataTables CSS -->

</head>
<body>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                  Fatura Türleri
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div style="width:50%; margin:0 auto" class="tablecontainerfaturaturleri">
                        <a class="popup btn btn-primary" href="~/FaturaTurleri/FaturaTurleriKayit/0" style="margin-bottom:20px; margin-top:20px;">Fatura Türü Ekle</a>
                        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-faturaturlerilist">
                            <thead>
                                <tr>
                                    <th>Fatura Türü</th>
                                    <th>Düzenle</th>
                                    <th>Sil</th>
                                </tr>
                            </thead>

                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>

    </div>

</body>
</html>

DevFramework.Northwind.MvcWebUI/Views/FaturaTurleri/FaturaTurleriSil.cshtml
@model DevFramework.Northwind.MvcWebUI.Models.FaturaTurleriListViewModel
@{
    Layout = null;
}


@using (Html.BeginForm("FaturaTurleriSil", "FaturaTurleri", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.faturaTurleriGet.Id)


    <div class="form-group">
        <label>Fatura Türü</label>
        <p>@Model.faturaTurleriGet.FaturaTuru adli fatura türü silinecektir.</p>
    </div>


    <div>
        <input class="btn btn-danger" type="submit" value="SİL" />
    </div>
}

DevFramework.Northwind.MvcWebUI/Views/FaturaTurleri/Index.cshtml
@{
    ViewBag.Title = "Fatura Türleri";
}

@Html.Partial("FaturaTurleriList")