DevFramework.Northwind.MvcWebUI/Models/KusakOdemeleriListViewModel.cs
using DevFramework.Northwind.Entities.ComplexTypes;
using DevFramework.Northwind.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DevFramework.Northwind.MvcWebUI.Models
{
    public class KusakOdemeleriListViewModel
    {
        public List<KusakOdemeleriDetay> kusakOdemleriDetays { get; set; }
        public List<KusakOdemeleri> kusakOdemleris { get; set; }
        public KusakOdemeleri kusakOdemeleriGet { get; set; }
        public KusakOdemeleriDetay kusakOdemeleriDetayGet { get; set; }
    }
}

DevFramework.Northwind.MvcWebUI/Controllers/KusakOdemeleriController.cs
using DevFramework.Northwind.Business.Abstract;
using DevFramework.Northwind.MvcWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DevFramework.Northwind.MvcWebUI.Controllers
{
    public class KusakOdemeleriController : Controller
    {
        private IKusaklarService _kusaklarService;
        private IKusakOdemeleriService _kusakOdemleriService;
        public KusakOdemeleriController(IKusakOdemeleriService kusakOdemleriService, IKusaklarService kusaklarService)
        {
            _kusakOdemleriService = kusakOdemleriService;
            _kusaklarService = kusaklarService;
        }
        // GET: KusakOdemeleri
        public ActionResult Index(int ?id)
        {
            Session["sporcuid"] = id;
            return View();
        }

        public ActionResult KusakOdemeleriGetir(int Id)
        {
            var model = new KusakOdemeleriListViewModel
            {
                kusakOdemleriDetays = _kusakOdemleriService.GetKusakOdemleriDetay().Where(i=>i.SporcuId==Id).ToList()
            };
            return Json(new { data = model.kusakOdemleriDetays }, JsonRequestBehavior.AllowGet);

        }
        //kusakları getirme forma
        [HttpGet]
        public ActionResult KusakOdemeleriKayit(int Id)
        {
            //kusaklar  drobdowlisti doldurma
            var modelkusak = new KusaklarListViewModel
            {
                kusaklars = _kusaklarService.GetAll()
            };
            ViewBag.kusaklargoster = modelkusak.kusaklars.OrderByDescending(i => i.Id);

            //kusaklar detay listeleme
            var model = new KusakOdemeleriListViewModel
            {
               kusakOdemeleriGet =_kusakOdemleriService.GetById(Id)
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult KusakOdemeleriKayit(KusakOdemeleriListViewModel kusakodemeleris)
        {
            bool status = false;
            if (ModelState.IsValid)
            {

                if (kusakodemeleris.kusakOdemeleriGet.Id > 0)
                {
                    //Edit 
                    var model = new KusakOdemeleriListViewModel
                    {
                        kusakOdemeleriGet = _kusakOdemleriService.Update(kusakodemeleris.kusakOdemeleriGet)
                    };
                }
                else
                {
                    kusakodemeleris.kusakOdemeleriGet.SporcuId =Convert.ToInt32(Session["sporcuid"]);
                    //Save
                    var model = new KusakOdemeleriListViewModel
                    {
                        kusakOdemeleriGet = _kusakOdemleriService.Add(kusakodemeleris.kusakOdemeleriGet)
                    };

                }

                status = true;

            }
            return new JsonResult { Data = new { status = status } };
        }

        [HttpGet]
        public ActionResult KusakOdemeleriSil(int id)
        {
            var model = new KusakOdemeleriListViewModel
            {
                kusakOdemeleriGet = _kusakOdemleriService.GetById(id)
            };
            return View(model);
        }
        //kusaklari sil
        [HttpPost]
        [ActionName("KusakOdemeleriSil")]
        public ActionResult Delete(int id)
        {
            bool status = false;
            if (id != 0)
            {
                _kusakOdemleriService.Delete(id);
                status = true;
            }

            return new JsonResult { Data = new { status = status } };
        }

    }
}

DevFramework.Northwind.MvcWebUI/Views/KusakOdemeleri/Index.cshtml
@{
    ViewBag.Title = "Kuşak Ödemeleri";
}
@Html.Partial("KusakOdemeleriList")

DevFramework.Northwind.MvcWebUI/Views/KusakOdemeleri/KusakOdemeleriKayit.cshtml
@model DevFramework.Northwind.MvcWebUI.Models.KusakOdemeleriListViewModel
@{
    Layout = null;
}


@using (Html.BeginForm("KusakOdemeleriKayit", "KusakOdemeleri", FormMethod.Post, new { id = "popupForm" }))
{

    if (Model.kusakOdemeleriGet != null && Model.kusakOdemeleriGet.Id > 0)
    {
        @Html.HiddenFor(a => a.kusakOdemeleriGet.Id)
        @Html.HiddenFor(a => a.kusakOdemeleriGet.SporcuId)
    }
    @*<div class="form-group">
        <label>Ad Soyad</label>
        @Html.TextBoxFor(a => a.kusakOdemeleriGet., new { @class = "form-control", @required = "required" })
        @Html.ValidationMessageFor(a => a.kusakOdemeleriDetayGet.AdSoyad)
    </div>*@
    <div class="form-group">
        <label>Ödeme Tarihi</label>
        @Html.TextBoxFor(a => a.kusakOdemeleriGet.OdemeTarihi, new { @Value = (Model.kusakOdemeleriGet != null) ? Model.kusakOdemeleriGet.OdemeTarihi.ToString() : DateTime.Now.ToString("dd.MM.yyyy"), @class = "form-control"})
        @Html.ValidationMessageFor(a => a.kusakOdemeleriGet.OdemeTarihi)
    </div>
    <div class="form-group">
        <label>Ödeme Tutari</label>
        @Html.TextBoxFor(a => a.kusakOdemeleriGet.OdemeTutari, new { @class = "form-control"})
        @Html.ValidationMessageFor(a => a.kusakOdemeleriGet.OdemeTutari)
    </div>
    <div class="form-group">
        <label>Sporcu Kategori</label>
        @Html.DropDownListFor(a => a.kusakOdemeleriGet.KusakId, new SelectList(ViewBag.kusaklargoster, "Id", "KusakAdi"), "Seçiniz", new { @class = "form-control", @required = "required" })
        @Html.ValidationMessageFor(a => a.kusakOdemeleriGet.KusakId)
    </div>
    <div>
        <input class="btn btn-success" type="submit" value="KAYIT" />
    </div>
}

DevFramework.Northwind.MvcWebUI/Views/KusakOdemeleri/KusakOdemeleriList.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <title>title</title>
    <!-- DataTables CSS -->

</head>
<body>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Kuşaklar Ödemeleri
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div style="width:50%; margin:0 auto" class="tablecontainerkusakodemeleri">
                        <label id="kusakodemeleri-sporcuid" style="display:none">@Session["sporcuid"].ToString()</label>
                        <a class="popup btn btn-primary" href="~/KusakOdemeleri/KusakOdemeleriKayit/0" style="margin-bottom:20px; margin-top:20px;">Yeni Kuşak Ekle</a>
                        @*<a class="btn btn-danger" href="~/SporcuOdemeleri/aylik/@TempData["sporcuid"].ToString()" style="margin-bottom:20px; margin-top:20px;">Sporcu Aylik Ödemesine Dön</a>*@
                        <a class="btn btn-default" href="~/" style="margin-bottom:20px; margin-top:20px;">Sporcu Sayfasına Dön</a>
                        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-kusakodemelerilist">
                            <thead>
                                <tr>
                                    <th>Kuşak Adi</th>
                                    <th>Sporcu Adi</th>
                                    <th>Ödeme Tarihi</th>
                                    <th>Ödeme Tutarı</th>
                                    <th>Düzenle</th>
                                    <th>Sil</th>
                                </tr>
                            </thead>

                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>

    </div>

</body>
</html>

DevFramework.Northwind.MvcWebUI/Views/KusakOdemeleri/KusakOdemeleriSil.cshtml
@model DevFramework.Northwind.MvcWebUI.Models.KusakOdemeleriListViewModel
@{
    Layout = null;
}


@using (Html.BeginForm("KusakOdemeleriSil", "KusakOdemeleri", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.kusakOdemeleriGet.Id)


    <div class="form-group">
        <label>Silmek ister misiniz</label>
          
    </div>


    <div>
        <input class="btn btn-danger" type="submit" value="SİL" />
    </div>
}