DevFramework.Northwind.MvcWebUI/Models/TesisDemirbaslarListViewModel.cs
using DevFramework.Northwind.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DevFramework.Northwind.MvcWebUI.Models
{
    public class TesisDemirbaslarListViewModel
    {
        public List<TesisDemirbaslar> tesisDemirbaslars { get; set; }
        public TesisDemirbaslar tesisDemirbaslarGet { get; set; }
    }
}

DevFramework.Northwind.MvcWebUI/Controllers/TesisDemirbaslarController.cs
using DevFramework.Northwind.Business.Abstract;
using DevFramework.Northwind.MvcWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DevFramework.Northwind.MvcWebUI.Controllers
{
    public class TesisDemirbaslarController : Controller
    {
        private ITesisDemirbaslarService _tesisDemirbaslar;
        public TesisDemirbaslarController(ITesisDemirbaslarService tesisDemirbaslar)
        {
            _tesisDemirbaslar = tesisDemirbaslar;
        }
        // GET: TesisDemirbaslar
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult TesisDemirbaslarList()
        {
            return View();

        }
        public ActionResult TesisDemirbaslarGetir()
        {
            var model = new TesisDemirbaslarListViewModel
            {
                tesisDemirbaslars = _tesisDemirbaslar.GetAll()
            };
            return Json(new { data = model.tesisDemirbaslars }, JsonRequestBehavior.AllowGet);

        }

        //tesisdemirbas getirme forma
        [HttpGet]
        public ActionResult TesisDemirbaslarKayit(int id)
        {
            var model = new TesisDemirbaslarListViewModel
            {
                tesisDemirbaslarGet = _tesisDemirbaslar.GetById(id)
            };
            return View(model);
        }
        //tesisdemirbas kaydetme ve güncelleme action
        [HttpPost]
        public ActionResult TesisDemirbaslarKayit(TesisDemirbaslarListViewModel tesisDemirbas)
        {
            bool status = false;
            if (ModelState.IsValid)
            {

                if (tesisDemirbas.tesisDemirbaslarGet.Id > 0)
                {
                    //Edit 
                    var model = new TesisDemirbaslarListViewModel
                    {
                        tesisDemirbaslarGet = _tesisDemirbaslar.Update(tesisDemirbas.tesisDemirbaslarGet)
                    };
                }
                else
                {
                    //Save
                    var model = new TesisDemirbaslarListViewModel
                    {
                        tesisDemirbaslarGet = _tesisDemirbaslar.Add(tesisDemirbas.tesisDemirbaslarGet)
                    };

                }

                status = true;

            }
            return new JsonResult { Data = new { status = status } };
        }

        //tesisdemirbas göster 
        [HttpGet]
        public ActionResult TesisDemirbaslarSil(int id)
        {
            var model = new TesisDemirbaslarListViewModel
            {
                tesisDemirbaslarGet = _tesisDemirbaslar.GetById(id)
            };
            return View(model);
        }
        //tesisdemirbas sil
        [HttpPost]
        [ActionName("TesisDemirbaslarSil")]
        public ActionResult Delete(int id)
        {
            bool status = false;
            if (id != 0)
            {
                _tesisDemirbaslar.Delete(id);
                status = true;
            }

            return new JsonResult { Data = new { status = status } };
        }

    }
}

DevFramework.Northwind.MvcWebUI/Views/TesisDemirbaslar/Index.cshtml
@{
    ViewBag.Title = "Tesis Demirbaşlar";
}

@Html.Partial("TesisDemirbaslarList")

DevFramework.Northwind.MvcWebUI/Views/TesisDemirbaslar/TesisDemirbaslarKayit.cshtml
@model DevFramework.Northwind.MvcWebUI.Models.TesisDemirbaslarListViewModel
@{
    Layout = null;
}

@using (Html.BeginForm("TesisDemirbaslarKayit", "TesisDemirbaslar", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model.tesisDemirbaslarGet != null && Model.tesisDemirbaslarGet.Id > 0)
    {
        @Html.HiddenFor(a => a.tesisDemirbaslarGet.Id)
    }
    <div class="form-group">
        <label>Demirbaş Adı</label>
        @Html.TextBoxFor(a => a.tesisDemirbaslarGet.DemirBasAdi, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.tesisDemirbaslarGet.DemirBasAdi)
    </div>
    <div class="form-group">
        <label>Kullanım Yeri</label>
        @Html.TextBoxFor(a => a.tesisDemirbaslarGet.KullanimYeri, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.tesisDemirbaslarGet.KullanimYeri)
    </div>
    <div class="form-group">
        <label>Kullanım Amaçı</label>
        @Html.TextBoxFor(a => a.tesisDemirbaslarGet.KullanimAmaci, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.tesisDemirbaslarGet.KullanimAmaci)
    </div>
    <div class="form-group">
        <label>Alım Fiyatı</label>
        @Html.TextBoxFor(a => a.tesisDemirbaslarGet.AlimFiyati, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.tesisDemirbaslarGet.AlimFiyati)
    </div>
    <div class="form-group">
        <label>Son Ödeme</label>
        @Html.TextBoxFor(a => a.tesisDemirbaslarGet.KayitTarihi, "{0:d}", new { @class = "form-control", type = "date" })
        @Html.ValidationMessageFor(a =>  a.tesisDemirbaslarGet.KayitTarihi)
    </div>

    <div>
        <input class="btn btn-success" type="submit" value="KAYIT" />
    </div>
}

DevFramework.Northwind.MvcWebUI/Views/TesisDemirbaslar/TesisDemirbaslarList.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>title</title>
    <!-- DataTables CSS -->

</head>
<body>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Tesis Demirbaşları
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div style="width:70%; margin:0 auto" class="tablecontainertesisdemirbaslar">
                        <a class="popup btn btn-primary" href="~/TesisDemirbaslar/TesisDemirbaslarKayit/0" style="margin-bottom:20px; margin-top:20px;">Fatura Türü Ekle</a>
                        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-tesisdemirbaslarlist">
                            <thead>
                                <tr>
                                    <th>Demirbaş Adı</th>
                                    <th>Alım Fiyatı</th>
                                    <th>Kullanım Yeri</th>
                                    <th>Kullanım Amaçı</th>
                                    <th>Kayit Tarihi</th>
                                    <th>Düzenle</th>
                                    <th>Sil</th>
                                </tr>
                            </thead>

                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>

    </div>

</body>
</html>

DevFramework.Northwind.MvcWebUI/Views/TesisDemirbaslar/TesisDemirbaslarSil.cshtml
@model DevFramework.Northwind.MvcWebUI.Models.TesisDemirbaslarListViewModel
@{
    Layout = null;
}

@using (Html.BeginForm("TesisDemirbaslarSil", "TesisDemirbaslar", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.tesisDemirbaslarGet.Id)

    <div class="form-group">
        <label>Demirbaş Adı</label>
        <p>@Model.tesisDemirbaslarGet.DemirBasAdi</p>
    </div>
    <div class="form-group">
        <label>Kullanım Yeri</label>
        <p>@Model.tesisDemirbaslarGet.KullanimYeri</p>
    </div>
    <div class="form-group">
        <label>Kullanım Amaçı</label>
        <p>@Model.tesisDemirbaslarGet.KullanimAmaci</p>
    </div>
    <div class="form-group">
        <label>Alım Fiyatı</label>
        <p>@Model.tesisDemirbaslarGet.AlimFiyati</p>
    </div>



    <div>
        <input class="btn btn-danger" type="submit" value="SİL" />
    </div>
}