DevFramework.Northwind.MvcWebUI/Models/KusaklarListViewModel.cs
using DevFramework.Northwind.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DevFramework.Northwind.MvcWebUI.Models
{
    public class KusaklarListViewModel
    {
        public List<Kusaklar> kusaklars { get; set; }
        public Kusaklar kusaklarGet { get; set; }
    }
}

DevFramework.Northwind.MvcWebUI/Controllers/KusaklarController.cs
using DevFramework.Northwind.Business.Abstract;
using DevFramework.Northwind.MvcWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DevFramework.Northwind.MvcWebUI.Controllers
{
    public class KusaklarController : Controller
    {

        private IKusaklarService _kusaklarService;
        public KusaklarController(IKusaklarService kusaklarService)
        {
            _kusaklarService = kusaklarService;
        }
        // GET: Kusak
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult KusaklarList()
        {
            return View();

        }
        public ActionResult KusaklarGetir()
        {
            var model = new KusaklarListViewModel
            {
                kusaklars = _kusaklarService.GetAll()
            };
            return Json(new { data = model.kusaklars }, JsonRequestBehavior.AllowGet);

        }
        //kusakları getirme forma
        [HttpGet]
        public ActionResult KusaklarKayit(int id)
        {

            var model = new KusaklarListViewModel
            {
                kusaklarGet = _kusaklarService.GetById(id)
            };
            return View(model);
        }
        //kusak kaydetme ve güncelleme action
        [HttpPost]
        public ActionResult KusaklarKayit(KusaklarListViewModel kusaklars)
        {
            bool status = false;
            if (ModelState.IsValid)
            {

                if (kusaklars.kusaklarGet.Id > 0)
                {
                    //Edit 
                    var model = new KusaklarListViewModel
                    {
                        kusaklarGet = _kusaklarService.Update(kusaklars.kusaklarGet)
                    };
                }
                else
                {
                    //Save
                    var model = new KusaklarListViewModel
                    {
                        kusaklarGet = _kusaklarService.Add(kusaklars.kusaklarGet)
                    };

                }

                status = true;

            }
            return new JsonResult { Data = new { status = status } };
        }
        //kusaklari göster 
        [HttpGet]
        public ActionResult KusaklarSil(int id)
        {
            var model = new KusaklarListViewModel
            {
                kusaklarGet = _kusaklarService.GetById(id)
            };
            return View(model);
        }
        //kusaklari sil
        [HttpPost]
        [ActionName("KusaklarSil")]
        public ActionResult Delete(int id)
        {
            bool status = false;
            if (id != 0)
            {
                _kusaklarService.Delete(id);
                status = true;
            }

            return new JsonResult { Data = new { status = status } };
        }
    }
}

DevFramework.Northwind.MvcWebUI/Views/Kusaklar/Index.cshtml
@{
    ViewBag.Title = "Kuşaklar";
}

@Html.Partial("KusaklarList")

DevFramework.Northwind.MvcWebUI/Views/Kusaklar/KusaklarKayit.cshtml
@model DevFramework.Northwind.MvcWebUI.Models.KusaklarListViewModel
@{
    Layout = null;
}


@using (Html.BeginForm("KusaklarKayit", "Kusaklar", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model.kusaklarGet != null && Model.kusaklarGet.Id > 0)
    {
        @Html.HiddenFor(a => a.kusaklarGet.Id)
    }

    <div class="form-group">
        <label>Kuşak Adı</label>
        @Html.TextBoxFor(a => a.kusaklarGet.KusakAdi, new { @class = "form-control", @required = "required" })
        @Html.ValidationMessageFor(a => a.kusaklarGet.KusakAdi)
    </div>


    <div>
        <input class="btn btn-success" type="submit" value="KAYIT" />
    </div>
}

DevFramework.Northwind.MvcWebUI/Views/Kusaklar/KusaklarList.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>title</title>
    <!-- DataTables CSS -->

</head>
<body>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Kuşaklar 
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div style="width:50%; margin:0 auto" class="tablecontainerkusaklar">
                        <a class="popup btn btn-primary" href="~/Kusaklar/KusaklarKayit/0" style="margin-bottom:20px; margin-top:20px;">Yeni Kuşak Ekle</a>
                        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-kusaklarlist">
                            <thead>
                                <tr>
                                    <th>Kuşak Adi</th>
                                    <th>Düzenle</th>
                                    <th>Sil</th>
                                </tr>
                            </thead>

                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>

    </div>

</body>
</html>

DevFramework.Northwind.MvcWebUI/Views/Kusaklar/KusaklarSil.cshtml
@model DevFramework.Northwind.MvcWebUI.Models.KusaklarListViewModel
@{
    Layout = null;
}


@using (Html.BeginForm("KusaklarSil", "Kusaklar", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.kusaklarGet.Id)


    <div class="form-group">
        <label>Kuşak Adı</label>
        <p>@Model.kusaklarGet.KusakAdi adli kuşak silinecektir.</p>
    </div>


    <div>
        <input class="btn btn-danger" type="submit" value="SİL" />
    </div>
}